table PodVolumeHistorisch
	lineageTag: b0000008-0000-0000-0000-000000000001

	column Datum
		dataType: dateTime
		formatString: Long Date
		summarizeBy: none
		sourceColumn: Datum
		lineageTag: b0000008-0000-0000-0000-000000000002

	column RondeNr
		dataType: string
		summarizeBy: none
		sourceColumn: RondeNr
		lineageTag: b0000008-0000-0000-0000-000000000003

	column AantalStukken
		dataType: int64
		summarizeBy: none
		sourceColumn: AantalStukken
		lineageTag: b0000008-0000-0000-0000-000000000004

	partition PodVolumeHistorisch = m
		mode: import
		source =
				let
				    Bron = Folder.Files(RealisatieFolder & "historisch"),
				    #"Enkel csv" = Table.SelectRows(Bron, each Text.EndsWith([Name], ".csv")),
				    #"Bestanden ingelezen" = Table.AddColumn(#"Enkel csv", "Data", each Table.PromoteHeaders(Csv.Document([Content], [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]), [PromoteAllScalars=true])),
				    Gecombineerd = Table.Combine(#"Bestanden ingelezen"[Data]),
				    #"Type gewijzigd" = Table.TransformColumnTypes(Gecombineerd,{
				        {"Datum", type date}, {"RondeNr", type text}, {"AantalStukken", Int64.Type}
				    })
				in
				    #"Type gewijzigd"

	annotation PBI_ResultType = Table

